os:
  - linux
language: go
go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - master
jobs:
  allow_failures:
    - go: master
  fast_finish: true
script:
  - go test -v ./...
  - go vet ./...
